import WvNavbar from '@wevisdemo/ui/components/navbar';
import WvFooter from '@wevisdemo/ui/components/footer';
import WvContainer from '@wevisdemo/ui/components/container';
import type { NextPage } from 'next';
import Head from 'next/head';

import "@wevisdemo/ui/styles/components.css";
import "@wevisdemo/ui/styles/typography.css";
import Intro from '../components/intro';
import PartNav from '../components/part-nav';
import Part1 from '../components/part-1';
import Part2 from '../components/part-2';

const Home: NextPage = () => {
  return (
    <div className='bg-black-1 text-white'>
      <Head>
        <title>Wevis | Politics on Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WvNavbar title="politic" dark={true} />
      <Intro />
      <PartNav />
      <Part1 />
      <Part2 />
      <WvFooter dark={true} />
    </div>
  )
}

export default Home


// const TIMELINE_COLLECTION = [
//   {
//     party: "พลังประชารัฐ",
//     content: "",
//   },
//   {
//     party: "ภูมิใจไทย",
//     content: "",
//   },
//   {
//     party: "ประชาธิปัตย์",
//     content: "",
//   },
//   {
//     party: "เพื่อไทย",
//     content: "",
//   },
//   {
//     party: "อนาคตใหม่/ก้าวไกล",
//     content: "",
//   },
//   {
//     party: "เสรีรวมไทย",
//     content: "",
//   },
// ]