
import type { NextPage } from 'next';
import Head from 'next/head';

import dynamic from 'next/dynamic';

const Intro = dynamic(() => import('../components/intro'));
const PartNav = dynamic(() => import('../components/part-nav'));
const Part1 = dynamic(() => import('../components/part-1'));
const Part2 = dynamic(() => import('../components/part-2'));
const Part3 = dynamic(() => import('../components/part-3'));
const Outro = dynamic(() => import('../components/outro'));


const Home: NextPage = () => {
  return (
    <div className='bg-black-1 text-white'>
      <Head>
        <title>Wevis | Politics on Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <PartNav />
      <Part1 />
      <Part2 />
      <Part3 />
      <Outro />
    </div >
  )
}

export default Home


// const GOVERNMENT = [
//   {
//     party: "พลังประชารัฐ",
//     content: "",
//   },
//   {
//     party: "ภูมิใจไทย",
//     content: "",
//   },
//   {
//     party: "ประชาธิปัตย์",
//     content: "",
//   },
// ]
// const OPPOSITION = [
//   {
//     party: "เพื่อไทย",
//     content: "",
//   },
//   {
//     party: "อนาคตใหม่/ก้าวไกล",
//     content: "",
//   },
//   {
//     party: "เสรีรวมไทย",
//     content: "",
//   },
// ]