import WvNavbar from '@wevisdemo/ui/components/navbar';
import WvFooter from '@wevisdemo/ui/components/footer';
import WvContainer from '@wevisdemo/ui/components/container';
import type { NextPage } from 'next';
import Head from 'next/head';

import "@wevisdemo/ui/styles/components.css";
import "@wevisdemo/ui/styles/typography.css";
import Intro from '../components/intro';
import PartNav from '../components/part-nav';
import Part1 from '../components/part-1';

const Home: NextPage = () => {
  return (
    <div className='bg-black-1 text-white'>
      <Head>
        <title>Wevis | Politics on Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WvNavbar title="politic" dark={true} />
      <Intro />
      <PartNav />
      <Part1 />
      <WvFooter />
    </div>
  )
}

export default Home
